# Generated by Django 6.0.2 on 2026-04-29 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0010_alter_dishdetail_quantity'),
        ('mealplan', '0003_remove_shoppingitem_shopping_it_shoppin_1c62ed_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('shopping_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=255)),
                ('list_type', models.CharField(choices=[('week', 'Theo tuần'), ('day', 'Theo ngày')], max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='mealplan.mealplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shopping_list',
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Chưa mua'), ('bought', 'Đã mua')], default='pending', max_length=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='home.ingredient')),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shoppinglist.shoppinglist')),
            ],
            options={
                'db_table': 'shopping_item',
            },
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['user', 'list_type'], name='shopping_li_user_id_b6821d_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['user', 'created_date'], name='shopping_li_user_id_93eb7f_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['plan', 'list_type'], name='shopping_li_plan_id_5e753e_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingitem',
            index=models.Index(fields=['shopping', 'status'], name='shopping_it_shoppin_1c62ed_idx'),
        ),
    ]
